# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    @version_string = "3.3.3/28"

    changelog
    commit
    tag
    push
    create_release
  end

  def changelog
    @changelog =
      changelog_from_git_commits(
        between: ['origin/master', git_branch],
        pretty: '%s',
        date_format: 'short',
        merge_commit_filtering: 'exclude_merges'
      )
    @changelog =
      @changelog.split(/\n+/).uniq.delete_if do |x|
        x.include?('IGNORE') || x.include?('pull request') || x.include?('bump')
      end
    @changes_count = @changelog.count
    @changelog
  end

def commit
  message = "version bump #{@version_string}"
  sh "git add . && git commit -m 'version bump'"
  # commit_version_bump(message: @version_string, no_verify: true)
end

def tag
  @tag = "ALPHA/#{@version_string}"
  add_git_tag(tag: @tag)
end

def push
  push_to_git_remote
end

def create_release
  changes = @changelog
  set_github_release(
    name: @version_string,
    tag_name: @tag,
    commitish: "master",
    description: official_changelog
  )
end

def official_changelog
  @changelog.split(/\n+/).select do |x|
    x.downcase().include?("atlassian") ||
    x.downcase().include?("jira") ||
    x.downcase().include?("cai-") ||
    x.downcase().include?("qa") ||
    x.downcase().include?("sentry") ||
    x.downcase().include?("crash")
  end
  .join("\n")
end
end
