# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    @version_string = "3.3.3/25"

    changelog
    commit
    tag
    push
    create_release
  end

  def changelog
    @changelog =
      changelog_from_git_commits(
        between: ['origin/master', git_branch],
        pretty: '%s',
        date_format: 'short',
        merge_commit_filtering: 'exclude_merges'
      )
    @changelog =
      @changelog.split(/\n+/).uniq.delete_if do |x|
        x.include?('IGNORE') || x.include?('pull request') || x.include?('bump')
      end
    @changes_count = @changelog.count
    @changelog.join("\n")
  end

def commit
  message = "version bump #{@version_string}"
  sh "git add . && git commit -m 'version bump'"
  # commit_version_bump(message: @version_string, no_verify: true)
end

def tag
  @tag = "ALPHA/#{@version_string}"
  add_git_tag(tag: @tag)
end

def push
  push_to_git_remote
end

def create_release
  set_github_release(
    repository_name: 'Qutaibah/gitignore',
    api_token: 'c891229effdb8fee04827e42d817314c6ea0310e',
    name: @version_string,
    tag_name: @tag,
    commitish: "master",
    description: @changelog.join("\n")
  )
end
end
